on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

name: "Build & Release"

jobs:
  build:
    name: Build Apk
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"

      - name: Clean dependencies and install
        run: flutter clean && flutter pub get && flutter pub upgrade

      - name: Create generated files
        run: sh freezed-build.sh

      - name: Create .env file
        run: |
          echo 'apiUrl="${{ vars.API_URL }}"' >> .env

      - name: Generate env_options.dart file
        run: python3 generate_env.py

      - name: Generate APK
        run: flutter build apk --release

      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT  # Set version as output

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versionstep.outputs.version }}  # Use the correct output
          token: ${{ secrets.TOKEN }}
          artifacts: "build/app/outputs/apk/release/app-release.apk"
